"""
Data models for the AWS Lambda Architecture implementation.
These models define the structure of data flowing through the pipeline.
"""

from datetime import datetime, timezone
from decimal import Decimal
from typing import Annotated, Any, Dict, List, Optional

from pydantic import BaseModel, Field, PlainSerializer

DecimalField = Annotated[Decimal, PlainSerializer(lambda v: str(v), return_type=str)]
IsoDateTime = Annotated[datetime, PlainSerializer(lambda v: v.isoformat(), return_type=str)]


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class TickData(BaseModel):
    """Raw tick data from Polygon.io WebSocket"""
    symbol: str
    price: DecimalField = Field(..., description="Current price")
    volume: int = Field(..., description="Volume for this tick")
    timestamp: IsoDateTime = Field(..., description="Timestamp of the tick")
    exchange: Optional[str] = None
    conditions: Optional[List[int]] = None


class OHLCVData(BaseModel):
    """OHLCV candlestick data"""
    symbol: str
    open: DecimalField
    high: DecimalField
    low: DecimalField
    close: DecimalField
    volume: int
    timestamp: IsoDateTime
    interval: str = Field(..., description="Interval (e.g., '1m', '5m', '1h', '1d')")


class TechnicalIndicator(BaseModel):
    """Technical indicator value"""
    symbol: str
    indicator_type: str = Field(..., description="e.g., 'ema', 'rsi', 'macd'")
    value: DecimalField
    timestamp: IsoDateTime
    interval: str
    parameters: Dict[str, Any] = Field(default_factory=dict)


class TradingSignal(BaseModel):
    """Trading signal generated by strategy"""
    signal_id: str = Field(..., description="Unique signal identifier")
    symbol: str
    signal_type: str = Field(..., description="'BUY', 'SELL', 'HOLD'")
    strategy: str = Field(..., description="Strategy that generated the signal")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level 0-1")
    price: DecimalField = Field(..., description="Price when signal was generated")
    timestamp: IsoDateTime
    metadata: Dict[str, Any] = Field(default_factory=dict)


class MarketAlert(BaseModel):
    """Market alert/notification"""
    alert_id: str
    symbol: str
    alert_type: str = Field(..., description="'PRICE_BREAKOUT', 'VOLUME_SPIKE', etc.")
    message: str
    severity: str = Field(..., description="'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'")
    timestamp: IsoDateTime
    conditions: Dict[str, Any] = Field(default_factory=dict)


class BatchProcessingJob(BaseModel):
    """Batch processing job metadata"""
    job_id: str
    job_type: str = Field(..., description="'DAILY_OHLCV', 'RESAMPLING', 'INDICATORS'")
    status: str = Field(..., description="'PENDING', 'RUNNING', 'COMPLETED', 'FAILED'")
    start_time: IsoDateTime
    end_time: Optional[IsoDateTime] = None
    symbols_processed: List[str] = Field(default_factory=list)
    records_processed: int = 0
    error_message: Optional[str] = None


class StreamProcessingMetrics(BaseModel):
    """Metrics for stream processing"""
    stream_name: str
    records_per_second: float
    lag_seconds: float
    error_rate: float
    timestamp: IsoDateTime


class APIResponse(BaseModel):
    """Standard API response format"""
    success: bool
    data: Optional[Any] = None
    error: Optional[str] = None
    timestamp: IsoDateTime = Field(default_factory=_utcnow)
    request_id: Optional[str] = None


class LivePriceResponse(BaseModel):
    """Response for live price API"""
    symbol: str
    price: DecimalField
    change: Optional[DecimalField] = None
    change_percent: Optional[float] = None
    volume: Optional[int] = None
    timestamp: IsoDateTime
    source: str = Field(..., description="'CACHE', 'DATABASE', 'API'")


class HistoricalDataResponse(BaseModel):
    """Response for historical data API"""
    symbol: str
    interval: str
    data: List[OHLCVData]
    count: int
    timestamp: IsoDateTime = Field(default_factory=_utcnow)


class SignalResponse(BaseModel):
    """Response for trading signals API"""
    symbol: str
    signals: List[TradingSignal]
    count: int
    timestamp: IsoDateTime = Field(default_factory=_utcnow)
